### PR TITLE
Case insensitive moves

### PR DESCRIPTION
**Pull request by NealAJohnson**

### CODE REVIEW

**Comment by NealAJohnson** [comment]
@cjsaylor Noticed this when playing with a friend, wasn't sure if there was a downside to adding case insensitivity.

**Comment by NealAJohnson** [comment]
Whelp, I'll get it working in a test at some point. Gotta learn some Go first.

**Comment by NealAJohnson** [comment]
Got it running locally, noticed that a change would have to go into notil/chess and, upon digging into that, a notation exists that lets you use B to denote a bishop moving to a location. Seems the issue may not be as straightforward as I thought and (since I started playing chess literally 4 hours ago) I probably don't know enough to be making the change. Was fun to get it running locally and test some Go code. Two firsts in one day.

**Comment by cjsaylor** [comment]
@NealAJohnson An alternative approach would be to do the change to allow case insensitive moves, and then before sending it to the chess engine, you force the string to lower case.

See https://pkg.go.dev/strings#ToLower

**Comment by NealAJohnson** [comment]
Disappointed that didn't occur to me. I'll revisit this soon and do so.

**Pull request closed without merging**
